name: Monday Morning Scraper (Sunday Games)

on:
  schedule:
    # Runs every Monday at 8:00 AM PST (16:00 UTC)
    - cron: '0 16 * * 1'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install selenium pandas beautifulsoup4 requests matplotlib seaborn numpy
      
      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver
      
      - name: Run Monday scraper
        run: |
          echo "Starting Monday morning scraper..."
          python3 scrapers/automated_yahoo_scraper.py --headless --week $(python3 -c "from datetime import datetime; start = datetime(2025, 9, 4); print((datetime.now() - start).days // 7 + 1)") --day Sunday
      
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          
          # Only commit if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            WEEK=$(python3 -c "from datetime import datetime; start = datetime(2025, 9, 4); print((datetime.now() - start).days // 7 + 1)")
            git commit -m "🤖 Automated Monday scrape: Week $WEEK Sunday data - $(date +%Y-%m-%d)"
            git push
            echo "Changes pushed successfully!"
          fi
      
      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: monday-logs-${{ github.run_number }}
          path: logs/
          retention-days: 30